import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import '@fontsource/inter/400.css';
import '@fontsource/inter/500.css';
import '@fontsource/inter/600.css';
import './style.css';
import {api,Login,AuthConfig,User} from './auth';
import {dateOffset,daysLeft,Project,Member,Task,Store,today,uid,VALUES} from './model';

function Modal({title,children,close,wide=false}:{title:string;children:React.ReactNode;close:()=>void;wide?:boolean}) { const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close()},[]);return <dialog ref={ref} className={wide?'modal wide':'modal'} onCancel={e=>{e.preventDefault();close()}} onClick={e=>{if(e.target===e.currentTarget)close()}} aria-label={title}><div className="modal-head"><span className="modal-mark" aria-hidden="true">··</span><button className="close" onClick={close} aria-label="닫기">×</button></div><h2>{title}</h2>{children}</dialog>; }
function AddTask({onAdd,onCancel}:{onAdd:(title:string,due:string)=>Promise<boolean>;onCancel:()=>void}) {const [title,setTitle]=useState('');const[due,setDue]=useState('');return <form className="add-task" onSubmit={async e=>{e.preventDefault();if(title.trim()&&await onAdd(title.trim(),due)){setTitle('');setDue('');onCancel()}}}><input autoFocus aria-label="할 일 이름" placeholder="무엇을 할까요?" maxLength={100} value={title} onChange={e=>setTitle(e.target.value)} required/><div className="inline-fields"><input type="date" aria-label="할 일 마감일" value={due} onChange={e=>setDue(e.target.value)}/><button type="button" onClick={onCancel}>취소</button><button className="primary small" disabled={!title.trim()}>추가</button></div></form>}
const MEMBER_COLORS = ['#64c6ff', '#ffcd6c', '#00c978', '#ff3e00'];
function Eyes() { return <svg width="20" height="14" viewBox="0 0 20 14" fill="none" aria-hidden="true"><ellipse cx="5.5" cy="7" rx="4" ry="5.5" stroke="currentColor" strokeWidth="1.2"/><ellipse cx="14.5" cy="7" rx="4" ry="5.5" stroke="currentColor" strokeWidth="1.2"/><circle cx="6.5" cy="8" r="1.5" fill="currentColor"/><circle cx="15.5" cy="8" r="1.5" fill="currentColor"/></svg> }
function App({initial,user,preview,onLogout}:{initial:Store;user:User;preview:boolean;onLogout:()=>Promise<void>}) {
  const [data,setData]=useState(initial);
  const [busy,setBusy]=useState(false);
  const [view,setView]=useState<'lobby'|'project'|'archive'|'create'>('lobby');
  const [tab,setTab]=useState('team');
  const [filter,setFilter]=useState('all');
  const [adding,setAdding]=useState<string|null>(null);
  const [modal,setModal]=useState<'scope'|'goal'|'finish'|'join'|'invite'|null>(null);
  const [selected,setSelected]=useState<{memberId:string;taskId:string}|null>(null);
  const [toast,setToast]=useState('');
  const [storageError,setStorageError]=useState(false);
  const [celebrate,setCelebrate]=useState<string|null>(null);
  const switcher=useRef<HTMLDetailsElement>(null);
  const celebrationTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
  const project=data.projects.find(p=>p.id===data.activeId)||data.projects[0]||{id:'',ownerId:user.id,name:'내 팀프로젝트',course:'',due:today(),goal:'',members:[{...user,values:[],tasks:[]}],scope:[],later:[],excluded:[],initialScope:0,history:[],archived:false};
  const me=project.members.find(m=>m.id===user.id)||{...user,values:[],tasks:[]};
  useEffect(()=>{if(preview)try{localStorage.setItem('deoreonae-preview-v2',JSON.stringify(data));setStorageError(false)}catch{setStorageError(true)}},[data,preview]);
  useEffect(()=>{if(preview||busy)return;let cancelled=false;const refresh=async()=>{if(document.hidden)return;try{const d=await api<{projects:Project[]}>('/api/projects');if(!cancelled)setData(old=>({...old,projects:d.projects}))}catch{}};const timer=setInterval(refresh,5000);window.addEventListener('focus',refresh);return()=>{cancelled=true;clearInterval(timer);window.removeEventListener('focus',refresh)}},[preview,busy]);
  useEffect(()=>{if(new URLSearchParams(location.search).get('invite'))setModal('join')},[]);
  useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(t)}},[toast]);
  useEffect(()=>()=>{if(celebrationTimer.current)clearTimeout(celebrationTimer.current)},[]);
  useEffect(()=>{function closeMenu(e:MouseEvent){if(!switcher.current?.contains(e.target as Node))switcher.current?.removeAttribute('open')}function escape(e:KeyboardEvent){if(e.key==='Escape')switcher.current?.removeAttribute('open')}document.addEventListener('click',closeMenu);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('click',closeMenu);document.removeEventListener('keydown',escape)}},[]);
  function update(fn:(p:Project)=>Project){setData(d=>({...d,projects:d.projects.map(p=>p.id===project.id?fn(p):p)}))}
  async function change(action:string,payload:Record<string,unknown>,apply:(p:Project)=>Project):Promise<boolean>{
    if(busy)return false;setBusy(true);
    try{if(preview)update(apply);else{const d=await api<{projects:Project[]}>(`/api/projects/${project.id}/actions`,{action,...payload});setData(old=>({...old,projects:d.projects}))}return true}
    catch(e){setToast((e as Error).message);return false}finally{setBusy(false)}
  }
  const withTask=(mid:string,tid:string,fn:(t:Task)=>Task)=>(p:Project)=>({...p,members:p.members.map(m=>m.id===mid?{...m,tasks:m.tasks.map(t=>t.id===tid?fn(t):t)}:m)});
  async function toggle(mid:string,t:Task){if(project.archived||mid!==user.id)return;const ok=await change('task.update',{taskId:t.id,done:!t.done},withTask(mid,t.id,old=>({...old,done:!old.done})));if(ok&&!t.done){setCelebrate(t.id);if(celebrationTimer.current)clearTimeout(celebrationTimer.current);celebrationTimer.current=setTimeout(()=>setCelebrate(null),450)}}
  async function trace(mid:string,t:Task){if(project.archived)return;const ok=await change('trace',{taskId:t.id},withTask(mid,t.id,old=>({...old,traces:old.traces.includes(me.name)?old.traces:[...old.traces,me.name]})));if(ok)setToast('슬쩍 다녀왔어요.')}
  async function addTask(mid:string,title:string,due:string){if(mid!==user.id)return false;return change('task.add',{title,due},p=>({...p,members:p.members.map(m=>m.id===mid?{...m,tasks:[...m.tasks,{id:uid(),title,done:false,due,traces:[]}]}:m)}))}
  async function createRoom(p:Project){if(busy)return;setBusy(true);try{if(preview){setData(d=>({...d,projects:[p,...d.projects],activeId:p.id,memberId:user.id}))}else{const d=await api<{projects:Project[];projectId:string}>('/api/projects',{...p,values:p.members[0].values});setData({projects:d.projects,activeId:d.projectId,memberId:user.id})}setView('project');setTab('team');setFilter('all');setModal('invite')}catch(e){setToast((e as Error).message)}finally{setBusy(false)}}
  async function joinRoom(code:string){if(preview){setToast('실제 초대 링크는 Google 로그인 뒤에 사용할 수 있어요.');return false}if(busy)return false;setBusy(true);try{const d=await api<{projects:Project[];projectId:string}>('/api/join',{code});setData({projects:d.projects,activeId:d.projectId,memberId:user.id});setView('project');setTab('team');setFilter('all');history.replaceState(null,'',location.pathname);return true}catch(e){setToast((e as Error).message);return false}finally{setBusy(false)}}
  function openProject(p:Project){setData(d=>({...d,activeId:p.id,memberId:p.members.some(m=>m.id===d.memberId)?d.memberId:p.members[0].id}));setView('project');setTab('team');setFilter('all');setAdding(null);switcher.current?.removeAttribute('open')}
  function go(v:'lobby'|'project'|'archive'|'create'){setView(v);setAdding(null);switcher.current?.removeAttribute('open')}
  const taskRow=(m:Member,t:Task,detail=false)=><div className={'task-row '+(t.done?'done ':'')+(celebrate===t.id?'just-done':'')} key={t.id}>
    <button className="check" aria-label={`${t.title} ${t.done?'완료 취소':'완료'}`} aria-pressed={t.done} disabled={project.archived||m.id!==user.id||busy} onClick={()=>toggle(m.id,t)}>{t.done&&<svg width="14" height="14" viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="m3 8 3.2 3.2L13 4" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round"/></svg>}</button>
    <div className="task-content"><button className="task-title" onClick={()=>setSelected({memberId:m.id,taskId:t.id})}>{t.title}</button>{t.traces.length>0&&<span className="trace-text"><span className="trace-dot"/>{t.traces.join(', ')}님이 슬쩍 보고 갔어요.</span>}</div>
    {detail&&t.due&&<span className="due">{t.due===today()?'오늘':t.due.slice(5).replace('-','.')} </span>}
    {m.id!==me.id&&!t.done&&!project.archived&&<button className={'trace '+(t.traces.includes(me.name)?'left':'')} aria-label={`${t.title}에 흔적 남기기`} title="슬쩍 다녀가기" onClick={()=>trace(m.id,t)}><Eyes/></button>}
  </div>;
  const membersToShow=project.members.filter(m=>tab==='mine'?m.id===me.id:filter==='all'||m.id===filter);
  const weekday=new Date().toLocaleDateString('ko-KR',{month:'long',day:'numeric',weekday:'long'});
  return <div className="app">
    <header className="site-header"><div className="nav-inner">
      <button className="brand" onClick={()=>go('lobby')} aria-label="DDAK 홈">DDAK<span className="brand-dot">.</span></button>
      <details className="project-switcher" ref={switcher}><summary><span className="project-dot"/>{view==='project'?project.name:'내 팀프로젝트'}<span className="chevron">⌄</span></summary><div className="project-menu"><p>팀프로젝트</p>{data.projects.filter(p=>!p.archived).map(p=><button key={p.id} className={p.id===project.id?'current':''} onClick={()=>openProject(p)}>{p.name}{p.id===project.id&&<span>✓</span>}</button>)}<div className="menu-divider"/><button onClick={()=>go('lobby')}>내 팀프로젝트</button><button onClick={()=>go('create')}>＋ 새 팀플 시작</button><button onClick={()=>go('archive')}>지난 팀플</button></div></details>
      <details className="profile-menu"><summary><span className="profile-dot">{user.name.slice(0,1)}</span><span>{user.name}</span><span className="chevron">⌄</span></summary><div className="profile-dropdown"><span>{preview?'화면 미리보기':'Google 계정으로 로그인됨'}</span><button onClick={()=>onLogout().catch(e=>setToast(e.message))}>{preview?'로그인 화면으로':'로그아웃'}</button></div></details>
    </div></header>
    <main className="main-content">
      {preview&&<div className="preview-banner">화면 미리보기 · 실제 Google 로그인과 팀원 공유는 연결되지 않아요.<button onClick={()=>onLogout()}>나가기</button></div>}
      {view==='lobby'&&<div className="page lobby"><h1>내 팀프로젝트<span className="title-dot">.</span></h1>{data.projects.filter(p=>!p.archived).length===0?<section className="first-project"><span className="welcome-dots" aria-hidden="true"><i/><i/><i/></span><h2>아직 팀프로젝트가 없습니다.</h2><button className="primary" onClick={()=>go('create')}>팀프로젝트 만들기</button><button className="join-link" onClick={()=>setModal('join')}>초대 링크로 들어가기</button></section>:<><div className="lobby-actions"><button className="primary" onClick={()=>go('create')}>＋ 팀프로젝트 만들기</button><button className="quiet-button" onClick={()=>setModal('join')}>초대 링크로 들어가기</button></div><div className="room-list">{data.projects.filter(p=>!p.archived).map((p,i)=><article className="room-row" key={p.id}><span className="person-marker" style={{background:MEMBER_COLORS[i%4]}}/><div><button className="room-name" onClick={()=>openProject(p)}>{p.name}</button><p>{p.goal}</p><small>{p.members.map(m=>m.name).join(' · ')}{p.due&&' / '+p.due.slice(5).replace('-','.')} 마감</small></div><button className="quiet-button" onClick={()=>openProject(p)}>들어가기</button></article>)}</div></>}<button className="past-link" onClick={()=>go('archive')}>지난 팀플 보기</button></div>}
      {storageError&&<p className="storage-error" role="alert">지금은 브라우저에 저장되지 않아요. 저장 공간을 확인해 주세요.</p>}
      {view==='project'&&project.id&&<div className="page home-page">
        <div className="hello"><div><p className="small-project">{project.name}</p><h1>{project.archived?'지난 할 일':'할 일'}<span className="hello-dot" aria-hidden="true"/></h1></div><p className="today-note">{weekday}<span>{project.archived?'마무리한 팀플':daysLeft(project.due)>0?`${project.due.slice(5).replace('-','월 ')}일 마감 · ${daysLeft(project.due)}일 남았어요`:daysLeft(project.due)===0?'오늘 마감이에요':`${Math.abs(daysLeft(project.due))}일 전에 마감했어요`}</span></p></div>
        <div className="room-breadcrumb"><button onClick={()=>go('lobby')}>내 팀프로젝트</button><span>/</span><span>{project.name}</span>{!project.archived&&<button className="invite-link" onClick={()=>setModal('invite')}>친구 초대</button>}</div><section className="promise" aria-label="우리 약속"><div className="promise-line"><span className="promise-label">프로젝트 목표</span><p>{project.goal}</p>{!project.archived&&<button className="quiet-button" onClick={()=>setModal('goal')}>수정</button>}</div><div className="promise-line not-doing"><span className="promise-label">이번에는 하지 않기</span><p>{project.excluded.join(' · ')||'아직 정하지 않았어요'}</p></div></section>
        <section className="todos"><div className="list-toolbar"><div className="tabs" role="group" aria-label="할 일 보기"><button aria-pressed={tab==='team'} className={tab==='team'?'selected':''} onClick={()=>{setTab('team');setFilter('all');setAdding(null)}}>모두의 할 일</button><button aria-pressed={tab==='mine'} className={tab==='mine'?'selected':''} onClick={()=>{setTab('mine');setAdding(null)}}>내 할 일</button></div>{tab==='team'&&filter!=='all'?<button className="quiet-button" onClick={()=>setFilter('all')}>모두 보기</button>:<span className="together-note">{project.members.length}명이 같이</span>}</div>
          {tab==='team'&&<section className="our-plans" aria-labelledby="progress-goals"><div className="plans-heading"><h2 id="progress-goals">진행목표</h2>{!project.archived&&<button className="new-scope" onClick={()=>setModal('scope')}>＋ 새롭게 해볼 일</button>}</div><div className="plans-content"><section><h3><span className="scope-dot blue"/>하기로 한 것</h3><ul>{project.scope.map(s=><li key={s}>{s}</li>)}</ul></section><section><h3><span className="scope-dot yellow"/>여유가 있으면</h3><ul>{project.later.map(s=><li key={s}>{s}</li>)}</ul>{!project.later.length&&<p className="muted">정해둔 일이 없어요.</p>}</section><section><h3>이번에는 하지 않기</h3><ul>{project.excluded.map(s=><li key={s}>{s}</li>)}</ul></section></div></section>}
          <div className={'people-list '+(membersToShow.length===1?'single-person':'')}>{membersToShow.map(m=><section className="person" key={m.id} style={{'--member-color':MEMBER_COLORS[project.members.indexOf(m)%4]} as React.CSSProperties}>
            <header className="person-heading"><span className="person-marker"/><button className="person-name" onClick={()=>{setTab('team');setFilter(filter===m.id?'all':m.id)}} aria-label={`${m.name}의 할 일 보기`}>{m.name}</button>{m.id===me.id&&<span className="me-label">나</span>}<span className="fraction">{m.tasks.filter(t=>t.done).length}<span>/{m.tasks.length}</span></span></header>
            {tab==='mine'?['오늘','이번 주','그다음','완료한 일'].map(group=>{const ts=m.tasks.filter(t=>group==='완료한 일'?t.done:!t.done&&(group==='오늘'?!!t.due&&t.due<=today():group==='이번 주'?!t.due||(t.due>today()&&t.due<=dateOffset(7)):t.due>dateOffset(7)));return ts.length>0&&<div className="task-group" key={group}><h3>{group}</h3>{ts.map(t=>taskRow(m,t,true))}</div>}):<div className="task-list">{m.tasks.map(t=>taskRow(m,t))}</div>}
            {!m.tasks.length&&<p className="empty-line">아직 적어둔 일이 없어요.</p>}
            {!project.archived&&m.id===user.id&&(adding===m.id?<AddTask onAdd={(t,d)=>addTask(m.id,t,d)} onCancel={()=>setAdding(null)}/>:<button className="add-link" onClick={()=>setAdding(m.id)}>＋ 할 일 추가</button>)}
          </section>)}</div>
        </section>
        

        {project.history.length>0&&<details className="history"><summary>목표 변경 기록 <span>{project.history.length}</span></summary>{project.history.map((h,i)=><p key={i}><time>{h.date.slice(5).replace('-','.')}</time><span>{h.removed} 대신 {h.added}</span></p>)}</details>}
        <footer className="page-footer">{(project.archived||project.ownerId===user.id)&&<button className="quiet-button" onClick={()=>project.archived?go('archive'):setModal('finish')}>{project.archived?'지난 팀플 보기':'이번 팀플 마무리'}</button>}</footer>
      </div>}
      {view==='archive'&&<div className="page collection"><button className="back-link" onClick={()=>go('lobby')}>내 팀프로젝트로</button><h1>지난 팀프로젝트</h1>{data.projects.filter(p=>p.archived).map(p=><article className="project-line" key={p.id}><div><button className="project-name" onClick={()=>openProject(p)}>{p.name}</button><p>{p.members.map(m=>m.name).join(' · ')}</p><details className="archive-details"><summary>우리 기록 펼치기</summary><p>처음 약속한 일 {p.initialScope}개 · 마지막에 남긴 일 {p.scope.length}개 · 완료한 할 일 {p.members.flatMap(m=>m.tasks).filter(t=>t.done).length}개</p><h3>남긴 일</h3><p>{p.scope.join(' · ')}</p><h3>이번에는 덜어낸 일</h3><p>{p.excluded.join(' · ')||'없어요.'}</p><h3>완료한 할 일</h3><p>{p.members.flatMap(m=>m.tasks.filter(t=>t.done).map(t=>`${t.title} (${m.name})`)).join(' · ')||'완료 표시한 일이 없어요.'}</p><h3>남아 있던 할 일</h3><p>{p.members.flatMap(m=>m.tasks.filter(t=>!t.done).map(t=>`${t.title} (${m.name})`)).join(' · ')||'모두 마쳤어요.'}</p></details></div><button className="quiet-button" onClick={()=>openProject(p)}>열어보기</button></article>)}{!data.projects.some(p=>p.archived)&&<div className="empty-state"><span className="empty-dot"/><p>마무리한 팀프로젝트가 없습니다.</p></div>}</div>}
      {view==='create'&&<CreateProject user={user} busy={busy} cancel={()=>go('lobby')} onCreate={createRoom}/>}
    </main>
    {modal==='scope'&&<ScopeExchange project={project} close={()=>setModal(null)} save={async(added,removed)=>{const ok=await change('scope.exchange',{added,removed},p=>({...p,scope:p.scope.map(s=>s===removed?added:s),later:p.later.filter(s=>s!==added),excluded:[...p.excluded.filter(s=>s!==added&&s!==removed),removed],history:[...p.history,{added,removed,date:today()}]}));if(ok){setModal(null);setToast('우리 약속을 바꿔두었어요.')}}}/>}
    {modal==='goal'&&<GoalEdit project={project} close={()=>setModal(null)} save={async(goal,excluded)=>{const ok=await change('goal',{goal,excluded},p=>({...p,goal,excluded}));if(ok){setModal(null);setToast('약속을 적어두었어요.')}}}/>}
    {modal==='finish'&&<Modal title="이번 팀플, 여기까지?" close={()=>setModal(null)}><p className="modal-description">같이 한 일들을 ‘지난 팀플’에 남겨둘게요.</p><p className="finish-note">{project.members.flatMap(m=>m.tasks).some(t=>!t.done)?'미처 끝내지 못한 일도 그대로 남아 있어요.':'적어둔 할 일을 모두 마쳤네요.'}</p><div className="modal-actions"><button onClick={()=>setModal(null)}>조금 더 할게요</button><button className="primary" disabled={busy} onClick={async()=>{if(await change('archive',{},p=>({...p,archived:true}))){setModal(null);setView('archive')}}}>마무리하기</button></div></Modal>}
    {selected&&(()=>{const m=project.members.find(m=>m.id===selected.memberId);const t=m?.tasks.find(t=>t.id===selected.taskId);return m&&t?<TaskDetail key={t.id} member={m} task={t} readonly={project.archived||m.id!==user.id} close={()=>setSelected(null)} save={async(title,due)=>{if(await change('task.update',{taskId:t.id,title,due},withTask(m.id,t.id,old=>({...old,title,due}))))setSelected(null)}} toggle={()=>toggle(m.id,t)}/>:null})()}
    {modal==='join'&&<JoinRoom busy={busy} initial={new URLSearchParams(location.search).get('invite')||''} close={()=>setModal(null)} join={joinRoom}/>}
    {modal==='invite'&&<Modal title="팀원 초대" close={()=>setModal(null)}>{preview?<p className="modal-description">방 만들기 화면을 확인했어요. 실제 팀원 초대는 Google 로그인 연결 후 사용할 수 있어요.</p>:<><p className="modal-description">링크를 받은 친구가 Google로 로그인하면<br/>같은 목표를 보고 자기 할 일을 적을 수 있어요.</p><label className="field">초대 링크<input readOnly value={location.origin+'/?invite='+project.inviteCode} onFocus={e=>e.target.select()}/></label><div className="modal-actions"><button onClick={()=>setModal(null)}>닫기</button><button className="primary" onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+'/?invite='+project.inviteCode);setToast('초대 링크를 복사했어요.')}catch{setToast('위 링크를 선택해서 복사해 주세요.')}}}>링크 복사</button></div></>}</Modal>}
    {toast&&<div role="status" className="toast">{toast}</div>}
  </div>
}

function TaskDetail({member,task,readonly,close,save,toggle}:{member:Member;task:Task;readonly:boolean;close:()=>void;save:(t:string,d:string)=>void;toggle:()=>void}){const[title,setTitle]=useState(task.title);const[due,setDue]=useState(task.due);return <Modal title={`${member.name}의 할 일`} close={close}><form onSubmit={e=>{e.preventDefault();if(title.trim())save(title.trim(),due)}}><label className="field">할 일 이름<input autoFocus value={title} maxLength={100} onChange={e=>setTitle(e.target.value)} required disabled={readonly}/></label><label className="field">마감일<input type="date" value={due} onChange={e=>setDue(e.target.value)} disabled={readonly}/></label><button className="detail-complete" type="button" onClick={toggle} disabled={readonly}><span className={'check '+(task.done?'completed':'')}>{task.done?'✓':''}</span>{task.done?'완료했어요':'완료로 표시하기'}</button>{task.traces.length>0&&<p className="visit-note">{task.traces.join(', ')}님이 슬쩍 보고 갔어요.</p>}<div className="modal-actions"><button type="button" onClick={close}>닫기</button>{!readonly&&<button className="primary" disabled={!title.trim()}>저장하기</button>}</div></form></Modal>}
function GoalEdit({project,close,save}:{project:Project;close:()=>void;save:(g:string,e:string[])=>void}){const[goal,setGoal]=useState(project.goal);const[excluded,setExcluded]=useState(project.excluded.join('\n'));const lines=excluded.split('\n').map(s=>s.trim()).filter(Boolean);const conflict=lines.some(s=>project.scope.includes(s)||project.later.includes(s));return <Modal title="목표 수정" close={close}><form onSubmit={e=>{e.preventDefault();if(!conflict&&goal.trim())save(goal.trim(),[...new Set(lines)])}}><label className="field">프로젝트 목표<textarea autoFocus required maxLength={180} value={goal} onChange={e=>setGoal(e.target.value)}/></label><label className="field">이번에는 하지 않기 <small>한 줄에 하나씩 적어주세요.</small><textarea rows={4} value={excluded} onChange={e=>setExcluded(e.target.value)}/></label>{conflict&&<p className="form-error">이미 하기로 한 일이에요. ‘새롭게 해볼 일’에서 먼저 바꿔주세요.</p>}<div className="modal-actions"><button type="button" onClick={close}>취소</button><button className="primary" disabled={conflict||!goal.trim()}>저장</button></div></form></Modal>}
function ScopeExchange({project,close,save}:{project:Project;close:()=>void;save:(a:string,r:string)=>void}) {
  const [added,setAdded]=useState('');
  const [removed,setRemoved]=useState('');
  const [review,setReview]=useState(false);
  const valid=added.trim()&&!project.scope.includes(added.trim());
  return <Modal title={review?'이렇게 바꿔볼까요?':'하나 더 할까요?'} close={close}>
    {!review?<><label className="field scope-input">새롭게 해볼 일<input autoFocus placeholder="예: 프로모션 영상 만들기" maxLength={80} value={added} onChange={e=>setAdded(e.target.value)}/></label>
      {project.scope.includes(added.trim())&&<p className="form-error">이미 하기로 한 일이에요.</p>}
      <fieldset className="exchange-options"><legend>그럼 하나는 덜어내야 해요.</legend><p>대신 쉬어갈 일을 골라주세요.</p>{project.scope.map(s=><label key={s}><input type="radio" name="remove" checked={removed===s} onChange={()=>setRemoved(s)}/><span>{s}</span></label>)}<label className="skip-option"><input type="radio" name="remove" checked={removed==='__skip__'} onChange={()=>setRemoved('__skip__')}/><span>그냥 이번에는 추가하지 않기</span></label></fieldset>
      <div className="modal-actions"><button onClick={close}>닫기</button><button className="primary" disabled={removed!=='__skip__'&&(!valid||!removed)} onClick={()=>removed==='__skip__'?close():setReview(true)}>{removed==='__skip__'?'그대로 둘게요':'골랐어요'}</button></div>
    </>:<><div className="swap-preview"><div><span className="swap-sign">−</span><div><small>이번에는 덜어두기</small><p>{removed}</p></div></div><div><span className="swap-sign plus">＋</span><div><small>새롭게 해보기</small><p>{added.trim()}</p></div></div></div><p className="exchange-note">다른 약속은 그대로예요.<br/>관련된 할 일은 팀원과 같이 정리해 주세요.</p><div className="modal-actions"><button onClick={()=>setReview(false)}>다시 고르기</button><button className="primary" onClick={()=>save(added.trim(),removed)}>좋아요, 바꿀게요</button></div></>}
  </Modal>
}

function CreateProject({cancel,onCreate,user,busy}:{cancel:()=>void;onCreate:(p:Project)=>void;user:User;busy:boolean}) {
 const [step,setStep]=useState(1);const[name,setName]=useState('');const[course,setCourse]=useState('');const[due,setDue]=useState(dateOffset(14));const[values,setValues]=useState<string[]>([]);const[goal,setGoal]=useState('');const[scope,setScope]=useState('');const[later,setLater]=useState('');const[excluded,setExcluded]=useState('');
 const parse=(s:string)=>[...new Set(s.split('\n').map(v=>v.trim()).filter(Boolean))];const groups=[parse(scope),parse(later),parse(excluded)];const duplicate=groups.flat().length!==new Set(groups.flat()).size;
 return <div className="page creation"><button className="back-link" onClick={cancel}>내 팀프로젝트로</button><div className="creation-progress"><span className={step===1?'current':''}>1. 팀플 이름</span><i/><span className={step===2?'current':''}>2. 목표 설정</span></div><h1>{step===1?'팀프로젝트 만들기':'목표 설정'}</h1><form onSubmit={e=>{e.preventDefault();if(step===1){setStep(2);return}if(!busy&&!duplicate&&goal.trim()&&groups[0].length&&groups[2].length)onCreate({id:uid(),ownerId:user.id,name:name.trim(),course:course.trim(),due,goal:goal.trim(),members:[{id:user.id,name:user.name,values,tasks:[]}],scope:groups[0],later:groups[1],excluded:groups[2],initialScope:groups[0].length,history:[],archived:false})}}>
 {step===1?<><div className="project-fields"><label className="field full">팀프로젝트 이름<input autoFocus placeholder="예: 인터랙션 디자인 3조" required maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><label className="field">수업 이름 <small>선택</small><input placeholder="어떤 수업인가요?" maxLength={60} value={course} onChange={e=>setCourse(e.target.value)}/></label><label className="field">마감 날짜<input type="date" value={due} required onChange={e=>setDue(e.target.value)}/></label></div><div className="creator-note"><span className="person-marker" style={{background:'#64c6ff'}}/><span>{user.name}</span><small>방을 만드는 사람</small></div><p className="page-subtitle">팀원은 방을 만든 뒤 초대 링크로 들어올 수 있어요.</p><div className="modal-actions"><button type="button" onClick={cancel}>취소</button><button className="primary" disabled={!name.trim()||!due}>목표 설정</button></div></>:<><label className="field">프로젝트 목표<textarea autoFocus required placeholder="예: 수업 안에서 완성도 높은 프로토타입을 만든다." maxLength={180} value={goal} onChange={e=>setGoal(e.target.value)}/></label><div className="goal-presets">{['수업 안에서 완성도 높은 결과물을 만든다.','새로운 툴을 경험하고 무리하지 않고 마무리한다.','주요 화면에 집중한 프로토타입을 완성한다.'].map(v=><button type="button" key={v} className={goal===v?'chosen':''} onClick={()=>setGoal(v)}>{v}</button>)}</div><div className="form-section-heading"><h2>진행목표</h2><span>한 줄에 하나씩 적어주세요.</span></div><div className="scope-fields"><label className="field">이번에 한다<textarea required rows={5} placeholder={'사용자 인터뷰\n프로토타입\n발표 자료'} value={scope} onChange={e=>setScope(e.target.value)}/></label><label className="field">여유가 있으면<textarea rows={5} placeholder="모션 인터랙션" value={later} onChange={e=>setLater(e.target.value)}/></label><label className="field">이번에는 안 한다<textarea required rows={5} placeholder={'공모전 출품\n추가 기능 개발'} value={excluded} onChange={e=>setExcluded(e.target.value)}/></label></div><div className="form-section-heading"><h2>{user.name}님이 중요하게 생각하는 것</h2><span>선택</span></div><div className="value-choices">{VALUES.map(v=><button type="button" aria-pressed={values.includes(v)} className={values.includes(v)?'picked':''} key={v} onClick={()=>setValues(xs=>xs.includes(v)?xs.filter(x=>x!==v):[...xs,v])}><span>{values.includes(v)?'●':'○'}</span>{v}</button>)}</div>{duplicate&&<p className="form-error">같은 일은 한 곳에만 적어주세요.</p>}<div className="modal-actions"><button type="button" onClick={()=>setStep(1)} disabled={busy}>이전으로</button><button className="primary" disabled={busy||duplicate||!groups[0].length||!groups[2].length||!goal.trim()}>{busy?'만드는 중…':'팀프로젝트 만들기'}</button></div></>}
 </form></div>
}
function JoinRoom({close,join,initial='',busy}:{close:()=>void;join:(code:string)=>Promise<boolean>;initial?:string;busy:boolean}){const[value,setValue]=useState(initial);const[error,setError]=useState('');return <Modal title="팀프로젝트 참여" close={close}><form onSubmit={async e=>{e.preventDefault();let code=value.trim();try{if(code.startsWith('http'))code=new URL(code).searchParams.get('invite')||''}catch{code=''}if(!code){setError('초대 링크를 다시 확인해 주세요.');return}if(await join(code))close()}}><p className="modal-description">친구가 보내준 초대 링크를 붙여넣어 주세요.</p><label className="field">초대 링크<input autoFocus value={value} onChange={e=>setValue(e.target.value)} placeholder="초대 링크 또는 초대 코드" required/></label>{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" onClick={close}>닫기</button><button className="primary" disabled={busy||!value.trim()}>{busy?'들어가는 중…':'팀플 들어가기'}</button></div></form></Modal>}
function Root(){
 const started=useRef(false);const[config,setConfig]=useState<AuthConfig|null>(null);const[user,setUser]=useState<User|null>(null);const[initial,setInitial]=useState<Store|null>(null);const[preview,setPreview]=useState(false);const[error,setError]=useState('');
 async function fetchSession(){setError('');try{const c=await api<AuthConfig>('/api/session');setConfig(c);setUser(c.user);if(c.user){const d=await api<{projects:Project[]}>('/api/projects');setInitial({projects:d.projects,activeId:'',memberId:c.user.id})}}catch(e){setError((e as Error).message)}}
 useEffect(()=>{if(!started.current){started.current=true;fetchSession()}},[]);
 async function loggedIn(u:User){setUser(u);try{const d=await api<{projects:Project[]}>('/api/projects');setInitial({projects:d.projects,activeId:'',memberId:u.id})}catch(e){setError((e as Error).message)}}
 function startPreview(){const u={id:'preview-user',name:'미리보기'};let store:Store={projects:[],activeId:'',memberId:u.id};try{const raw=localStorage.getItem('deoreonae-preview-v2');if(raw){const parsed=JSON.parse(raw);if(Array.isArray(parsed.projects))store={...parsed,activeId:'',memberId:u.id}}}catch{}setPreview(true);setUser(u);setInitial(store)}
 async function logout(){if(!preview)await api('/api/auth/logout',{});window.google?.accounts.id.disableAutoSelect();setPreview(false);setUser(null);setInitial(null);await fetchSession()}
 if(error)return <div className="connection-error"><h1>잠깐, 연결을 확인할게요.</h1><p>{error}</p><button className="primary" onClick={()=>user?loggedIn(user):fetchSession()}>다시 연결</button></div>;
 if(!config||(user&&!initial))return <div className="loading-page" role="status">DDAK<span>잠깐만요…</span></div>;
 if(!user||!initial)return <Login config={config} onLogin={loggedIn} onPreview={startPreview}/>;
 return <App key={user.id+(preview?'preview':'live')} initial={initial} user={user} preview={preview} onLogout={logout}/>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><Root/></React.StrictMode>);
